const C=document.querySelector('#street'),X=C.getContext('2d');let W,H,dpr,started=0,ledgerOpen=0,dialogue=0,day=1,actions=5,pos=0,look=0,tab=0;
const houses=[
['Hart & Crown','Alehouse',[['Edmund Vale',47],['Joan Vale',44],['Ned Vale',19]],'clear',['Vale reports all within are well.']],
['Martha Bell','Seamstress',[['Martha Bell',33],['Eliza Bell',9]],'exposed',['Eliza seen playing beside the pump.']],
['Cooper Household','Cooper',[['Thomas Cooper',42],['Anne Cooper',39],['Mary Cooper',13],['William Cooper',7]],'infected',['Anne says William slept poorly.','A cough heard above stairs.']],
['Samuel Pike','Chandler',[['Samuel Pike',55],['Ruth Pike',51]],'clear',['Shop open before prime.']],
['Widow Harrow','Washerwoman',[['Agnes Harrow',61],['Kit Harrow',16]],'clear',['Requests relief bread.']],
['The Red Lion','Butcher',[['John Finch',38],['Sarah Finch',35],['Tom Finch',11]],'clear',['Meat cart arrived from Smithfield.']],
['Mercer Household','Printer',[['Robert Mercer',29],['Alice Mercer',27],['Infant Mercer',1]],'clear',['Infant heard crying; household active.']],
['Old Nan Croft','Herb seller',[['Anne Croft',68]],'clear',['Door ajar; rosemary hung at lintel.']]
].map((h,i)=>({n:i+1,name:h[0],trade:h[1],people:h[2],truth:h[3],notes:h[4],quarantine:false,dead:false}));
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*dpr;C.height=H*dpr;X.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function rnd(i){let x=Math.sin(i*999+17)*43758.5453;return x-Math.floor(x)}
function draw(){let t=performance.now()/1000,sky=X.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#aaa087');sky.addColorStop(.58,'#c7b78f');sky.addColorStop(1,'#655b48');X.fillStyle=sky;X.fillRect(0,0,W,H);let horizon=H*.42,vanish=W/2+look*90,rt=W*.17;X.fillStyle='#554c3d';X.beginPath();X.moveTo(vanish-rt/2,horizon);X.lineTo(vanish+rt/2,horizon);X.lineTo(W,H);X.lineTo(0,H);X.fill();
for(let side of [-1,1])for(let i=0;i<8;i++){let z=i+1,near=1/(z*.25+.15),bw=Math.min(W*.24,70*near),bh=Math.min(H*.72,145*near),depth=i/8,cx=vanish+side*(rt/2+(W*.47-rt/2)*(1-depth)),base=horizon+(H-horizon)*(1-depth*.82),x=cx+(side<0?-bw:0),hi=side<0?i:7-i;X.fillStyle=['#625646','#755f4d','#554d40'][i%3];X.fillRect(x,base-bh,bw,bh);X.strokeStyle='#2b251e';X.lineWidth=Math.max(1,near);X.strokeRect(x,base-bh,bw,bh);for(let f=0;f<3;f++)for(let w=0;w<2;w++){let wx=x+bw*(.18+w*.46),wy=base-bh*(.28+f*.25),ww=bw*.18,wh=bh*.12;X.fillStyle='#29251f';X.fillRect(wx,wy,ww,wh);if(!houses[hi].dead&&rnd(i*5+f)>.35){X.fillStyle='rgba(214,174,105,'+(.07+.04*Math.sin(t+i))+')';X.fillRect(wx+2,wy+2,ww-4,wh-4)}}if(houses[hi].quarantine){X.strokeStyle='#7c2d24';X.lineWidth=Math.max(2,near*2);X.beginPath();X.moveTo(x+bw*.35,base-bh*.18);X.lineTo(x+bw*.65,base-bh*.06);X.moveTo(x+bw*.65,base-bh*.18);X.lineTo(x+bw*.35,base-bh*.06);X.stroke()}}
X.fillStyle='rgba(225,215,185,.09)';X.fillRect(0,0,W,H);requestAnimationFrame(draw)}draw();
const q=s=>document.querySelector(s),nearest=()=>Math.max(0,Math.min(7,Math.round((pos+look*.4)%8)));
function hud(){let h=houses[nearest()];q('#date').textContent='DAY '+day+' · '+(17+day)+' JUNE 1665';q('#actions').textContent=actions+' matters may yet be attended';q('#prompt').innerHTML=started&&!ledgerOpen&&!dialogue?'No. '+h.n+' · '+h.name+'<br><b>E</b> KNOCK':''}hud();
q('#begin').onclick=()=>{started=1;q('#intro').style.opacity=0;setTimeout(()=>q('#intro').style.display='none',1400);hud()};
function toggleLedger(){ledgerOpen=!ledgerOpen;q('#ledger').classList.toggle('open',ledgerOpen);if(ledgerOpen)renderLedger();hud()}q('#ledgerBtn').onclick=toggleLedger;q('#closeLedger').onclick=toggleLedger;
function renderLedger(){q('#ledgerDate').textContent=(17+day)+' June, in the seventeenth year of His Majesty';q('#houseTabs').innerHTML=houses.map((h,i)=>'<button data-i="'+i+'" class="'+(i===tab?'activeTab':'')+'">'+h.n+'</button>').join('');q('#houseTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tab=+b.dataset.i;renderLedger()});let h=houses[tab];q('#folio').innerHTML='<h3>No. '+h.n+' — '+h.name+'</h3><div class="trade">'+h.trade+'</div>'+h.people.map(p=>'<div class="person">'+p[0]+' · '+p[1]+'</div>').join('')+'<h4>Observations</h4>'+h.notes.map(n=>'<div class="note">'+n+'</div>').join('')+(h.quarantine?'<div class="note">House ordered shut by parish authority.</div>':'')+'<p class="uncertain">The book records testimony and observation. It does not record certainty.</p>'}
function knock(){if(dialogue||actions<1)return;let h=houses[nearest()];dialogue=1;actions--;let suspicious=h.truth==='infected',line=suspicious?'“We are quite well, sir. The boy has only taken a chill. There is no cause to shut us in.”':'“God keep you. We are well enough today. Is there news from the next parish?”';q('#speaker').textContent='NO. '+h.n+' · '+h.name;q('#speech').textContent=line;q('#choices').innerHTML='<button id="observe">Observe</button><button id="shut">Order house shut</button><button id="leave">Take your leave</button>';q('#dialogue').style.display='block';q('#observe').onclick=()=>{h.notes.push(suspicious?'During questioning: speaker avoids the upper floor; coughing heard.':'During questioning: no obvious sign of sickness observed.');closeTalk()};q('#shut').onclick=()=>{h.quarantine=true;h.notes.push('House ordered shut on '+(17+day)+' June.');closeTalk()};q('#leave').onclick=closeTalk;hud()}
function closeTalk(){dialogue=0;q('#dialogue').style.display='none';if(actions===0)night();hud()}
function night(){day++;actions=5;houses.forEach((h,i)=>{if(h.truth==='infected'&&Math.random()<.32){h.notes.push('Morning: shutters remain closed. No one answers at first knock.');if(day>4&&Math.random()<.3)h.dead=true}if(h.truth==='exposed'&&Math.random()<.22)h.truth='infected'});if(day>14){day=14;actions=0}}
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key.toLowerCase()==='l')toggleLedger();if(e.key.toLowerCase()==='e'&&started&&!ledgerOpen)knock()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);setInterval(()=>{if(!started||ledgerOpen||dialogue)return;if(keys.w||keys.arrowup)pos=(pos+.035)%8;if(keys.s||keys.arrowdown)pos=(pos+7.965)%8;if(keys.a||keys.arrowleft)look=Math.max(-1,look-.025);if(keys.d||keys.arrowright)look=Math.min(1,look+.025);hud()},16);
let drag=null;C.onpointerdown=e=>drag=e.clientX;C.onpointerup=()=>drag=null;C.onpointermove=e=>{if(drag!==null){look=Math.max(-1,Math.min(1,look+(e.clientX-drag)/400));drag=e.clientX;hud()}};