const C=document.querySelector('#street'),X=C.getContext('2d'),q=s=>document.querySelector(s);let W,H,D,started=0,ledgerOpen=0,dialogue=0,day=1,actions=5,pos=0,look=0,tab=0,last=0,step=0;
const HOUSES=[
['Hart & Crown','Alehouse',[['Edmund Vale',47],['Joan Vale',44],['Ned Vale',19]],'clear',['Vale reports all within are well.'],.72],
['Martha Bell','Seamstress',[['Martha Bell',33],['Eliza Bell',9]],'exposed',['Eliza seen playing beside the pump.'],.88],
['Cooper Household','Cooper',[['Thomas Cooper',42],['Anne Cooper',39],['Mary Cooper',13],['William Cooper',7]],'infected',['Anne says William slept poorly.','A cough heard above stairs.'],.48],
['Samuel Pike','Chandler',[['Samuel Pike',55],['Ruth Pike',51]],'clear',['Shop open before prime.'],.91],
['Widow Harrow','Washerwoman',[['Agnes Harrow',61],['Kit Harrow',16]],'clear',['Requests relief bread.'],.65],
['The Red Lion','Butcher',[['John Finch',38],['Sarah Finch',35],['Tom Finch',11]],'clear',['Meat cart arrived from Smithfield.'],.77],
['Mercer Household','Printer',[['Robert Mercer',29],['Alice Mercer',27],['Infant Mercer',1]],'clear',['Infant heard crying; household active.'],.84],
['Old Nan Croft','Herb seller',[['Anne Croft',68]],'clear',['Door ajar; rosemary hung at lintel.'],.95]
].map((h,i)=>({n:i+1,name:h[0],trade:h[1],people:h[2].map(p=>({name:p[0],age:p[1],alive:true})),truth:h[3],notes:h[4],honesty:h[5],quarantine:false,shut:false,seed:i*31+7}));
function rnd(i){let x=Math.sin(i*9283.17+17.3)*43758.5453;return x-Math.floor(x)}function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*D;C.height=H*D;X.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function poly(a,fill,stroke='#241f19',lw=1){X.beginPath();X.moveTo(a[0][0],a[0][1]);a.slice(1).forEach(p=>X.lineTo(p[0],p[1]));X.closePath();X.fillStyle=fill;X.fill();if(stroke){X.strokeStyle=stroke;X.lineWidth=lw;X.stroke()}}
function drawHouse(x,base,bw,bh,h,side,near,t){let lean=(rnd(h.seed)-.5)*bw*.12,wall=['#71614e','#665848','#806956','#5d5548'][h.n%4],timber='#29251f';poly([[x,base],[x+lean,base-bh],[x+bw+lean,base-bh],[x+bw,base]],wall,timber,Math.max(1,near*.8));let roof=rnd(h.seed+2)>.45?.2:.12;poly([[x+lean-bw*.08,base-bh],[x+lean+bw*.5,base-bh-bh*roof],[x+lean+bw*1.08,base-bh]],'#38332b',timber,Math.max(1,near));X.strokeStyle=timber;X.lineWidth=Math.max(1,near*1.5);for(let f=1;f<3;f++){let y=base-bh*f/3;X.beginPath();X.moveTo(x,y);X.lineTo(x+bw,y);X.stroke()}for(let v=0;v<4;v++){let xx=x+bw*v/3;X.beginPath();X.moveTo(xx,base);X.lineTo(xx+lean,base-bh);X.stroke()}let alive=h.people.some(p=>p.alive),active=alive&&!h.shut;for(let f=0;f<2;f++)for(let w=0;w<2;w++){let wx=x+bw*(.17+w*.48)+lean*(.3+f*.3),wy=base-bh*(.38+f*.29),ww=bw*.18,wh=bh*.12;X.fillStyle='#211f1b';X.fillRect(wx,wy,ww,wh);if(active&&rnd(h.seed+f*9+w+day)>.23){X.fillStyle='rgba(210,171,101,'+(.08+.035*Math.sin(t+h.seed))+')';X.fillRect(wx+2,wy+2,ww-4,wh-4);X.strokeStyle='#b8aa88';X.lineWidth=.6;X.beginPath();X.moveTo(wx+ww/2,wy);X.lineTo(wx+ww/2,wy+wh);X.moveTo(wx,wy+wh/2);X.lineTo(wx+ww,wy+wh/2);X.stroke()}}let dw=bw*.2,dh=bh*.2,dx=x+bw*.5-dw/2;X.fillStyle='#30291f';X.fillRect(dx,base-dh,dw,dh);if(h.n===1||h.n===6){X.fillStyle='#b18b55';X.fillRect(x+bw*(side<0?.72:.05),base-bh*.38,bw*.22,bh*.045)}if(h.quarantine){X.strokeStyle='#7d2e25';X.lineWidth=Math.max(2,near*2.4);X.beginPath();X.moveTo(dx-dw*.25,base-dh*.75);X.lineTo(dx+dw*1.25,base-dh*.2);X.moveTo(dx+dw*1.25,base-dh*.75);X.lineTo(dx-dw*.25,base-dh*.2);X.stroke();X.fillStyle='#8b3c2e';X.font=Math.max(7,near*5)+'px Georgia';X.fillText('LORD HAVE MERCY',dx-dw*.3,base-dh*.82)}if(day<4&&active&&rnd(h.seed+day)>.52){X.fillStyle='#8d8165';X.beginPath();X.arc(x+bw*.5,base+near*4,Math.max(1,near*2.2),0,7);X.fill()}}
function draw(tms){let t=tms/1000,loss=(day-1)/13,morning=Math.max(0,.7-loss*.25),sky=X.createLinearGradient(0,0,0,H);sky.addColorStop(0,`rgb(${158-loss*35},${153-loss*31},${134-loss*26})`);sky.addColorStop(.58,`rgb(${190-loss*42},${174-loss*40},${139-loss*32})`);sky.addColorStop(1,'#615746');X.fillStyle=sky;X.fillRect(0,0,W,H);let sunX=W*.72,sunY=H*.18;X.fillStyle=`rgba(235,205,145,${.18*(1-loss*.5)})`;X.beginPath();X.arc(sunX,sunY,W*.06,0,7);X.fill();let horizon=H*.38,vanish=W/2+look*W*.07,rt=W*.115;X.fillStyle='#51493b';poly([[vanish-rt/2,horizon],[vanish+rt/2,horizon],[W,H],[0,H]],'#51493b',null);X.strokeStyle='rgba(28,25,21,.28)';for(let i=0;i<18;i++){let y=horizon+(H-horizon)*i/18;X.beginPath();X.moveTo(vanish-(y-horizon)*.8,y);X.lineTo(vanish+(y-horizon)*.8,y+3);X.stroke()}
for(let side of [-1,1])for(let i=7;i>=0;i--){let depth=i/8,z=i+1,near=1/(z*.21+.13),bw=Math.min(W*.25,78*near),bh=Math.min(H*.78,(150+rnd(i+side)*35)*near),cx=vanish+side*(rt/2+(W*.48-rt/2)*(1-depth)),base=horizon+(H-horizon)*(1-depth*.82),x=cx+(side<0?-bw:0),hi=side<0?i:7-i;drawHouse(x,base,bw,bh,HOUSES[hi],side,near,t)}
X.strokeStyle='rgba(40,34,27,.55)';X.lineWidth=1;for(let i=0;i<5;i++){let y=H*(.17+i*.035);X.beginPath();X.moveTo(0,y+rnd(i)*20);X.quadraticCurveTo(W/2,y+30,W,y-5);X.stroke();for(let j=0;j<8;j++){let xx=W*j/7+rnd(j+i)*30,yy=y+Math.sin(j)*12;X.fillStyle=['#77634e','#9b8b6a','#6e765e'][j%3];X.fillRect(xx,yy,18+rnd(j)*18,3+rnd(i)*5)}}
if(day<5){X.fillStyle='#8a7d60';for(let i=0;i<Math.max(1,6-day);i++){let xx=W*.18+rnd(i+day)*W*.64,yy=H*.69+rnd(i*3)*H*.18;X.beginPath();X.arc(xx,yy,3+rnd(i)*3,0,7);X.fill()}}if(day>5){X.fillStyle=`rgba(37,33,28,${.035*loss})`;X.fillRect(0,0,W,H)}X.fillStyle='rgba(225,215,185,.055)';X.fillRect(0,0,W,H);requestAnimationFrame(draw)}requestAnimationFrame(draw);
const nearest=()=>Math.max(0,Math.min(7,Math.round((pos+look*.35)%8)));function hud(){let h=HOUSES[nearest()];q('#date').textContent='DAY '+day+' · '+(17+day)+' JUNE 1665';q('#actions').textContent=actions?actions+' matters may yet be attended':'THE DAY IS SPENT';q('#prompt').innerHTML=started&&!ledgerOpen&&!dialogue?'No. '+h.n+' · '+h.name+'<br><b>E</b> KNOCK':''}hud();
q('#begin').onclick=()=>{started=1;q('#intro').style.opacity=0;setTimeout(()=>q('#intro').style.display='none',1400);hud()};function toggleLedger(){ledgerOpen=!ledgerOpen;q('#ledger').classList.toggle('open',ledgerOpen);if(ledgerOpen)renderLedger();hud()}q('#ledgerBtn').onclick=toggleLedger;q('#closeLedger').onclick=toggleLedger;
function renderLedger(){q('#ledgerDate').textContent=(17+day)+' June, in the seventeenth year of His Majesty';q('#houseTabs').innerHTML=HOUSES.map((h,i)=>'<button data-i="'+i+'" class="'+(i===tab?'activeTab':'')+'">'+h.n+'</button>').join('');q('#houseTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tab=+b.dataset.i;renderLedger()});let h=HOUSES[tab];q('#folio').innerHTML='<h3>No. '+h.n+' — '+h.name+'</h3><div class="trade">'+h.trade+'</div>'+h.people.map(p=>'<div class="person">'+p.name+' · '+p.age+(p.alive?'':' — <em>buried</em>')+'</div>').join('')+'<h4>Observations</h4>'+h.notes.map(n=>'<div class="note">'+n+'</div>').join('')+(h.quarantine?'<div class="note red">House ordered shut by parish authority.</div>':'')+'<p class="uncertain">This book records testimony and observation. It does not record certainty.</p>'}
function knock(){if(dialogue||actions<1)return;let h=HOUSES[nearest()];dialogue=1;actions--;let sick=h.truth==='infected',speaker=h.people.find(p=>p.alive);let line=!speaker?'No answer. The house is very still.':sick?(Math.random()<h.honesty?'“The little one has a fever. Please—do not shut us in without bread.”':'“We are quite well, sir. It is only a summer chill.”'):(h.n===5?'“If the parish has bread to spare, Kit and I have eaten nothing since yesterday.”':'“God keep you. We are well enough today. Is there news from the next parish?”');q('#speaker').textContent='NO. '+h.n+' · '+h.name;q('#speech').textContent=line;q('#choices').innerHTML='<button id="observe">Observe closely</button><button id="relief">Leave relief</button><button id="shut">Order house shut</button><button id="leave">Take your leave</button>';q('#dialogue').style.display='block';q('#observe').onclick=()=>{h.notes.push(sick?'During questioning: heat in the face; coughing heard beyond the speaker.':'During questioning: no obvious sign of sickness observed.');closeTalk()};q('#relief').onclick=()=>{h.notes.push('Relief bread left at the door on '+(17+day)+' June.');closeTalk()};q('#shut').onclick=()=>{h.quarantine=true;h.notes.push('House ordered shut on '+(17+day)+' June.');closeTalk()};q('#leave').onclick=closeTalk;hud()}
function closeTalk(){dialogue=0;q('#dialogue').style.display='none';if(actions===0)setTimeout(night,350);hud()}function night(){if(day>=14)return;day++;actions=5;HOUSES.forEach((h,i)=>{if(h.truth==='exposed'&&rnd(day*19+i)>.55)h.truth='infected';if(h.truth==='infected'){if(!h.quarantine&&rnd(day*31+i)>.62){let n=HOUSES[(i+1)%8];if(n.truth==='clear')n.truth='exposed'}if(rnd(day*43+i)>.72){let p=h.people.find(p=>p.alive);if(p){p.alive=false;h.notes.push((17+day)+' June — '+p.name+' taken before dawn.');h.shut=!h.people.some(p=>p.alive)}}}});hud()}
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key.toLowerCase()==='l')toggleLedger();if(e.key.toLowerCase()==='e'&&started&&!ledgerOpen)knock()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);setInterval(()=>{if(!started||ledgerOpen||dialogue)return;if(keys.w||keys.arrowup)pos=(pos+.03)%8;if(keys.s||keys.arrowdown)pos=(pos+7.97)%8;if(keys.a||keys.arrowleft)look=Math.max(-1,look-.02);if(keys.d||keys.arrowright)look=Math.min(1,look+.02);hud()},16);let drag=null;C.onpointerdown=e=>drag=e.clientX;C.onpointerup=()=>drag=null;C.onpointercancel=()=>drag=null;C.onpointermove=e=>{if(drag!==null){look=Math.max(-1,Math.min(1,look+(e.clientX-drag)/360));drag=e.clientX;hud()}};